version: '3'

#networks:
#
#  redisnet:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 10.0.0.0/16

services:

  redis-cluster:
    image: redis:5.0.9
    command: redis-cli -p 6379 -h 172.16.0.23 -a test123 --cluster create 172.16.0.23:6379 172.16.0.23:6380 172.16.0.23:26379 172.16.0.23:26380 172.16.0.23:46379 172.16.0.23:46380 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    network_mode: host

  redis-1:
    build: ./redis
    image: redis-cluster-node
    restart: always
    environment:
      X_REDIS_PORT: 6379
    network_mode: host
    ports:
      - 6379:6379
    volumes:
      - /data/6379/data:/data

  redis-2:
    image: redis-cluster-node
    restart: always
    environment:
      X_REDIS_PORT: 6380
    network_mode: host
    ports:
      - 6380:6380
    volumes:
      - /data/6380/data:/data

  redis-3:
    image: redis-cluster-node
    restart: always
    environment:
      X_REDIS_PORT: 26379
    network_mode: host
    ports:
      - 26379:26379
    volumes:
      - /data/16379/data:/data

  redis-4:
    image: redis-cluster-node
    restart: always
    environment:
      X_REDIS_PORT: 26380
    network_mode: host
    ports:
      - 26380:26380
    volumes:
      - /data/16380/data:/data

  redis-5:
    image: redis-cluster-node
    restart: always
    environment:
      X_REDIS_PORT: 46379
    network_mode: host
    ports:
      - 46379:46379
    volumes:
      - /data/26379/data:/data

  redis-6:
    image: redis-cluster-node
    restart: always
    environment:
      X_REDIS_PORT: 46380
    network_mode: host
    ports:
      - 46380:46380
    volumes:
      - /data/26380/data:/data
