version: '3'

networks:

  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16

services:

  redis-cluster:
    image: redis:5.0.9
    command: redis-cli -p 6379 --cluster -a test123 create 10.0.0.11:6379 10.0.0.12:6380 10.0.0.13:16379 10.0.0.14:16380 10.0.0.15:26379 10.0.0.16:26380 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    networks:
      redisnet:
        ipv4_address: 10.0.0.2

  redis-1:
    build: ./redis
    image: redis-cluster-node
    restart: always
    environment:
      X_REDIS_PORT: 6379
    networks:
      redisnet:
        ipv4_address: 10.0.0.11
    ports:
      - 6379:6379
    volumes:
      - /data/6379/data:/data

  redis-2:
    image: redis-cluster-node
    restart: always
    environment:
      X_REDIS_PORT: 6380
    networks:
      redisnet:
        ipv4_address: 10.0.0.12
    ports:
      - 6380:6379
    volumes:
      - /data/6380/data:/data

  redis-3:
    image: redis-cluster-node
    restart: always
    environment:
      X_REDIS_PORT: 16379
    networks:
      redisnet:
        ipv4_address: 10.0.0.13
    ports:
      - 16379:6379
    volumes:
      - /data/16379/data:/data

  redis-4:
    image: redis-cluster-node
    restart: always
    environment:
      X_REDIS_PORT: 16380
    networks:
      redisnet:
        ipv4_address: 10.0.0.14
    ports:
      - 16380:6379
    volumes:
      - /data/16380/data:/data

  redis-5:
    image: redis-cluster-node
    restart: always
    environment:
      X_REDIS_PORT: 26379
    networks:
      redisnet:
        ipv4_address: 10.0.0.15
    ports:
      - 26379:6379
    volumes:
      - /data/26379/data:/data

  redis-6:
    image: redis-cluster-node
    restart: always
    environment:
      X_REDIS_PORT: 26380
    networks:
      redisnet:
        ipv4_address: 10.0.0.16
    ports:
      - 26380:6379
    volumes:
      - /data/26380/data:/data
